# Generated by Django 5.0.1 on 2025-05-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_chapter_unique_chapter_order_per_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseenrollment',
            name='progress_percent',
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='progress',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
