# Generated by Django 5.0.1 on 2025-05-09 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_remove_courseenrollment_progress_percent_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lesson',
            name='unique_lesson_order_per_chapter',
        ),
        migrations.AddField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='academy.course'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='lesson',
            constraint=models.UniqueConstraint(fields=('course', 'order'), name='unique_lesson_order_per_course'),
        ),
    ]
