# Generated by Django 5.0.1 on 2025-05-12 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_remove_lesson_unique_lesson_order_per_chapter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonprogress',
            name='watched_seconds',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
