# Generated by Django 5.0.1 on 2024-04-06 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(default=9999)),
                ('name', models.CharField(max_length=256, verbose_name='專案/競賽/課程名稱')),
                ('award', models.CharField(default='', max_length=256, verbose_name='名次/獎項')),
            ],
        ),
    ]
