# Generated by Django 5.0.1 on 2024-04-06 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=256, verbose_name='聯絡人')),
                ('contact_need', models.CharField(max_length=20, verbose_name='需求')),
                ('contact_phone', models.CharField(max_length=64, verbose_name='聯絡電話')),
                ('contact_email', models.CharField(max_length=128, verbose_name='聯絡信箱')),
                ('contact_message', models.CharField(max_length=1024, verbose_name='聯絡訊息')),
                ('contact_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
