# Generated by Django 5.0.1 on 2024-04-06 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_contact_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='collect_email',
            fields=[
                ('email', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='聯絡信箱')),
                ('collect_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
