# Generated by Django 5.0.1 on 2024-04-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_collect_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='collect_email',
            name='is_subscribed',
            field=models.BooleanField(default=True),
        ),
    ]
