# Generated by Django 5.0.1 on 2024-01-31 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogpost", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="column",
            options={
                "ordering": ["name"],
                "verbose_name": "主題",
                "verbose_name_plural": "主題",
            },
        ),
    ]
