# Generated by Django 5.0.1 on 2024-01-31 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogpost", "0002_alter_column_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="column",
            options={},
        ),
    ]
