# Generated by Django 5.0.1 on 2024-02-01 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogpost", "0003_alter_column_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
