# Generated by Django 5.0.1 on 2024-02-21 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogpost", "0004_alter_article_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="bar_img_link",
            field=models.CharField(
                default="/static/bootstrap/assets/img/blog/single_blog_11.png",
                max_length=2560,
                verbose_name="圖片連結",
            ),
        ),
    ]
