# Generated by Django 5.0.1 on 2024-03-18 03:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="課程主題名稱")),
                (
                    "slug",
                    models.CharField(
                        db_index=True, max_length=256, unique=True, verbose_name="主題網址"
                    ),
                ),
                ("intro", models.TextField(default="", verbose_name="主題簡介")),
                ("display", models.BooleanField(default=False, verbose_name="主題顯示")),
            ],
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=256, verbose_name="課程名稱")),
                ("subtitle", models.CharField(max_length=256, verbose_name="課程副標題")),
                (
                    "slug",
                    models.CharField(
                        db_index=True, max_length=256, unique=True, verbose_name="課程網址"
                    ),
                ),
                (
                    "img_link",
                    models.CharField(
                        default="/static/story/assets/AI_free_logo.png",
                        max_length=2560,
                        verbose_name="課程圖片連結",
                    ),
                ),
                (
                    "bar_img_link",
                    models.CharField(
                        default="/static/bootstrap/assets/img/blog/single_blog_11.png",
                        max_length=2560,
                        verbose_name="課程圖片連結",
                    ),
                ),
                (
                    "pub_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="課程上架時間"),
                ),
                (
                    "update_time",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="課程更新時間"
                    ),
                ),
                ("content", models.TextField(default="", verbose_name="內文")),
                ("published", models.BooleanField(default=True, verbose_name="正式發布")),
                (
                    "Category",
                    models.ManyToManyField(to="course.category", verbose_name="歸屬主題"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作者",
                    ),
                ),
            ],
        ),
    ]
