# Generated by Django 5.0.1 on 2024-03-18 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lesson",
            old_name="Category",
            new_name="cate",
        ),
    ]
