# Generated by Django 5.0.1 on 2024-03-18 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0002_rename_category_lesson_cate"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="price",
            field=models.PositiveIntegerField(default=9999),
        ),
    ]
