# Generated by Django 5.0.1 on 2024-03-18 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0003_lesson_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="rating",
            field=models.FloatField(default=5.0),
        ),
    ]
